// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/productOrder.proto

package orders

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string       `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	OrderItems           []*OrderItem `protobuf:"bytes,4,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_92fea8a1c70b0f1e, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetOrderItems() []*OrderItem {
	if m != nil {
		return m.OrderItems
	}
	return nil
}

type OrderItem struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UnitPrice            float32  `protobuf:"fixed32,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Quantity             int32    `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderItem) Reset()         { *m = OrderItem{} }
func (m *OrderItem) String() string { return proto.CompactTextString(m) }
func (*OrderItem) ProtoMessage()    {}
func (*OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_92fea8a1c70b0f1e, []int{1}
}

func (m *OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItem.Unmarshal(m, b)
}
func (m *OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItem.Marshal(b, m, deterministic)
}
func (m *OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItem.Merge(m, src)
}
func (m *OrderItem) XXX_Size() int {
	return xxx_messageInfo_OrderItem.Size(m)
}
func (m *OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItem proto.InternalMessageInfo

func (m *OrderItem) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *OrderItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderItem) GetUnitPrice() float32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *OrderItem) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type OrderResponse struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92fea8a1c70b0f1e, []int{2}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Order)(nil), "Order")
	proto.RegisterType((*OrderItem)(nil), "OrderItem")
	proto.RegisterType((*OrderResponse)(nil), "OrderResponse")
}

func init() {
	proto.RegisterFile("protos/productOrder.proto", fileDescriptor_92fea8a1c70b0f1e)
}

var fileDescriptor_92fea8a1c70b0f1e = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4b, 0x84, 0x40,
	0x14, 0xc6, 0xd3, 0x55, 0xcb, 0x67, 0xed, 0x61, 0x88, 0x98, 0xdd, 0x08, 0xc4, 0x4b, 0x42, 0xa0,
	0xb0, 0x1d, 0x3a, 0x06, 0x75, 0xea, 0x54, 0xd8, 0x2d, 0x82, 0xc5, 0xf4, 0x11, 0x73, 0x70, 0xc6,
	0x66, 0x9e, 0x41, 0xff, 0x7d, 0xf8, 0xd4, 0x85, 0xbd, 0x7d, 0xbf, 0x4f, 0x7c, 0xbf, 0x79, 0x0f,
	0x36, 0xbd, 0x35, 0x64, 0x5c, 0xd9, 0x5b, 0xd3, 0x0e, 0x0d, 0xbd, 0xda, 0x16, 0x6d, 0xc1, 0x5d,
	0xf6, 0x09, 0x21, 0xa3, 0x58, 0x83, 0xaf, 0x5a, 0xe9, 0xa5, 0x5e, 0x1e, 0x57, 0xbe, 0x6a, 0xc5,
	0x15, 0x44, 0x8e, 0x6a, 0x1a, 0x9c, 0xf4, 0xb9, 0x9b, 0x49, 0xdc, 0x41, 0x62, 0xc6, 0x1f, 0xf6,
	0x8a, 0xb0, 0x73, 0x32, 0x48, 0x57, 0x79, 0xb2, 0x83, 0x82, 0x87, 0xbc, 0x10, 0x76, 0x15, 0x98,
	0x25, 0xba, 0x4c, 0x43, 0x7c, 0xf8, 0x20, 0x04, 0x04, 0x8d, 0x69, 0x71, 0x76, 0x70, 0x1e, 0x3b,
	0x5d, 0x77, 0x38, 0x3b, 0x38, 0x8b, 0x1b, 0x80, 0x41, 0x2b, 0xda, 0xf7, 0x56, 0x35, 0x28, 0x57,
	0xa9, 0x97, 0xfb, 0x55, 0x3c, 0x36, 0x6f, 0x63, 0x21, 0xb6, 0x70, 0xf6, 0x33, 0xd4, 0x9a, 0x14,
	0xfd, 0xc9, 0x20, 0xf5, 0xf2, 0xb0, 0x3a, 0x70, 0xf6, 0x08, 0x17, 0xec, 0xab, 0xd0, 0xf5, 0x46,
	0x3b, 0x14, 0x12, 0x4e, 0xa7, 0xe7, 0x2c, 0xab, 0x2d, 0x28, 0x2e, 0x21, 0x44, 0x6b, 0x8d, 0x9d,
	0xd5, 0x13, 0xec, 0x1e, 0xe0, 0x9c, 0x07, 0xbc, 0xa3, 0xfd, 0x1d, 0x65, 0xb7, 0x90, 0x3c, 0x5b,
	0xac, 0x09, 0xa7, 0x23, 0x45, 0xd3, 0x9e, 0xdb, 0x75, 0x71, 0xa4, 0xc9, 0x4e, 0x9e, 0xae, 0x3f,
	0x36, 0x45, 0x51, 0x36, 0xa6, 0xeb, 0x8c, 0x2e, 0xbf, 0x51, 0xf3, 0x75, 0x4b, 0x96, 0xb9, 0xaf,
	0x88, 0xe9, 0xfe, 0x3f, 0x00, 0x00, 0xff, 0xff, 0xe3, 0xae, 0x2f, 0xe4, 0x88, 0x01, 0x00, 0x00,
}
